import { ReviewTemplate } from '@/lib/templates/types'

export function generateMarkdown(
  template: ReviewTemplate,
  responses: Record<string, string>,
  completedAt: Date
): string {
  const year = completedAt.getFullYear()
  const formattedDate = completedAt.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  let markdown = `# ${template.name} - ${year}\n\n`
  markdown += `> ${template.intro.headline}\n\n`
  markdown += `**Completed**: ${formattedDate}\n`
  markdown += `**Template by**: ${template.creator.name}`
  if (template.creator.title) {
    markdown += ` (${template.creator.title})`
  }
  markdown += `\n\n---\n\n`

  let currentSection = ''
  for (const question of template.questions) {
    if (question.section && question.section !== currentSection) {
      currentSection = question.section
      markdown += `## ${currentSection}\n\n`
    }

    const answer = responses[question.id] || '_No response_'
    markdown += `### ${question.text}\n\n`
    markdown += `${answer}\n\n`
  }

  markdown += `---\n\n`
  markdown += `*Generated by Annual Review Vault*\n`

  return markdown
}

export function downloadMarkdown(content: string, filename: string): void {
  const blob = new Blob([content], { type: 'text/markdown' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
