import { ReviewTemplate } from './types'

export const gustinTemplate: ReviewTemplate = {
  slug: 'gustin-annual-review',
  name: "Dr. Anthony Gustin's Annual Review",
  creator: {
    name: 'Dr. Anthony Gustin',
    title: 'Founder of Perfect Keto',
    bio: 'A comprehensive 6-step framework for deep life reflection and intentional goal-setting.',
    websiteUrl: 'https://dranthonygustin.com',
  },
  intro: {
    headline: 'Design Your Year With Intention',
    description: 'This deep-dive review guides you through reflecting on the past year, auditing your current life, and setting meaningful goals for the year ahead. Plan for 2-3 hours of focused reflection.',
    estimatedMinutes: 150,
  },
  questions: [
    // STEP 1: HOUSEKEEPING
    {
      id: 'environment-setup',
      text: 'Before you begin: Have you set up your environment for deep reflection?',
      type: 'select',
      section: 'Step 1: Housekeeping',
      options: [
        'Yes - I have 2-3 hours blocked, devices away, and a quiet space',
        'Partially - I have some time but may be interrupted',
        'No - I\'ll do my best in the time I have',
      ],
      helpText: 'This review works best with uninterrupted focus time.',
    },
    {
      id: 'reflection-materials',
      text: 'What materials will help you reflect? (journals, photos, calendars, etc.)',
      type: 'textarea',
      section: 'Step 1: Housekeeping',
      placeholder: 'List any resources you\'ll reference during this review...',
    },

    // STEP 2: REFLECT
    {
      id: 'highlight-reel',
      text: 'What were your highlights from this past year?',
      type: 'textarea',
      section: 'Step 2: Reflect on the Past Year',
      placeholder: 'Think about moments that made you feel alive, proud, or grateful...',
      helpText: 'Include personal wins, professional achievements, relationships, experiences.',
      required: true,
    },
    {
      id: 'accomplishments',
      text: 'What did you accomplish that you\'re most proud of?',
      type: 'textarea',
      section: 'Step 2: Reflect on the Past Year',
      placeholder: 'List your biggest wins and achievements...',
      required: true,
    },
    {
      id: 'growth-areas',
      text: 'How did you grow as a person this year?',
      type: 'textarea',
      section: 'Step 2: Reflect on the Past Year',
      placeholder: 'Consider skills, mindsets, habits, relationships...',
    },
    {
      id: 'challenges-faced',
      text: 'What were your biggest challenges, and how did you handle them?',
      type: 'textarea',
      section: 'Step 2: Reflect on the Past Year',
      placeholder: 'Describe obstacles you faced and what you learned...',
      required: true,
    },
    {
      id: 'lessons-learned',
      text: 'What are the most important lessons you learned this year?',
      type: 'textarea',
      section: 'Step 2: Reflect on the Past Year',
      placeholder: 'Insights about life, work, relationships, yourself...',
      required: true,
    },
    {
      id: 'regrets',
      text: 'What do you wish you had done differently?',
      type: 'textarea',
      section: 'Step 2: Reflect on the Past Year',
      placeholder: 'Be honest - this is for your growth...',
    },
    {
      id: 'grateful-for',
      text: 'What are you most grateful for from this year?',
      type: 'textarea',
      section: 'Step 2: Reflect on the Past Year',
      placeholder: 'People, experiences, opportunities, growth...',
      required: true,
    },
    {
      id: 'word-of-year',
      text: 'If you had to describe this year in one word, what would it be?',
      type: 'text',
      section: 'Step 2: Reflect on the Past Year',
      placeholder: 'One word that captures the essence of your year...',
    },
    {
      id: 'year-rating',
      text: 'On a scale of 1-10, how would you rate this year overall?',
      type: 'scale',
      section: 'Step 2: Reflect on the Past Year',
      minValue: 1,
      maxValue: 10,
      helpText: '1 = Terrible, 10 = Best year ever',
    },
    {
      id: 'rating-explanation',
      text: 'Why did you give it that rating?',
      type: 'textarea',
      section: 'Step 2: Reflect on the Past Year',
      placeholder: 'What contributed to this score?',
    },

    // STEP 3: REVIEW OUTCOMES
    {
      id: 'previous-goals-review',
      text: 'What goals did you set for this year, and how did you do?',
      type: 'textarea',
      section: 'Step 3: Review Outcomes',
      placeholder: 'List last year\'s goals and your progress on each...',
      helpText: 'Be specific about what you achieved vs. what you didn\'t.',
    },
    {
      id: 'goal-obstacles',
      text: 'What prevented you from achieving goals you missed?',
      type: 'textarea',
      section: 'Step 3: Review Outcomes',
      placeholder: 'Identify patterns, obstacles, or reasons...',
    },
    {
      id: 'unexpected-achievements',
      text: 'What did you achieve that you didn\'t plan for?',
      type: 'textarea',
      section: 'Step 3: Review Outcomes',
      placeholder: 'Sometimes the best things are unplanned...',
    },
    {
      id: 'habits-assessment',
      text: 'Which habits served you well, and which held you back?',
      type: 'textarea',
      section: 'Step 3: Review Outcomes',
      placeholder: 'Positive habits to keep, negative habits to change...',
    },
    {
      id: 'relationships-impact',
      text: 'How did your relationships evolve this year?',
      type: 'textarea',
      section: 'Step 3: Review Outcomes',
      placeholder: 'New connections, deepened bonds, relationships that changed...',
    },
    {
      id: 'energy-audit',
      text: 'What gave you energy this year? What drained you?',
      type: 'textarea',
      section: 'Step 3: Review Outcomes',
      placeholder: 'Activities, people, environments that energized vs. depleted you...',
    },

    // STEP 4: WHERE YOU ARE NOW
    {
      id: 'current-life-satisfaction',
      text: 'Rate your current satisfaction in each life area (1-10):',
      type: 'textarea',
      section: 'Step 4: Where You Are Now',
      placeholder: 'Health: /10\nRelationships: /10\nCareer: /10\nFinances: /10\nPersonal Growth: /10\nFun & Recreation: /10\nPhysical Environment: /10\nContribution: /10',
      helpText: 'Be honest about where you truly are, not where you wish you were.',
      required: true,
    },
    {
      id: 'ideal-day',
      text: 'Describe your ideal typical day, from waking up to going to bed.',
      type: 'textarea',
      section: 'Step 4: Where You Are Now',
      placeholder: 'Walk through your perfect day in detail...',
    },
    {
      id: 'current-day-gap',
      text: 'How does your current typical day compare to your ideal?',
      type: 'textarea',
      section: 'Step 4: Where You Are Now',
      placeholder: 'What\'s aligned? What\'s misaligned?',
    },
    {
      id: 'ideal-week',
      text: 'What does your ideal week look like?',
      type: 'textarea',
      section: 'Step 4: Where You Are Now',
      placeholder: 'How do you want to spend your time across the week?',
    },
    {
      id: 'purpose-clarity',
      text: 'How clear are you on your life purpose right now?',
      type: 'scale',
      section: 'Step 4: Where You Are Now',
      minValue: 1,
      maxValue: 10,
      helpText: '1 = Completely unclear, 10 = Crystal clear',
    },
    {
      id: 'purpose-statement',
      text: 'Attempt to articulate your current understanding of your purpose.',
      type: 'textarea',
      section: 'Step 4: Where You Are Now',
      placeholder: 'Even if unclear, write what you know...',
    },
    {
      id: 'core-values',
      text: 'What are your core values? Are you living in alignment with them?',
      type: 'textarea',
      section: 'Step 4: Where You Are Now',
      placeholder: 'List your top 5 values and assess alignment...',
    },

    // STEP 5: WHAT DO YOU WANT
    {
      id: 'year-theme',
      text: 'What theme or word do you want to define next year?',
      type: 'text',
      section: 'Step 5: What Do You Want',
      placeholder: 'One word or phrase to guide your year...',
      required: true,
    },
    {
      id: 'theme-meaning',
      text: 'What does this theme mean to you? Why did you choose it?',
      type: 'textarea',
      section: 'Step 5: What Do You Want',
      placeholder: 'Explain the significance of your chosen theme...',
    },
    {
      id: 'vision-next-year',
      text: 'Describe your ideal life one year from now.',
      type: 'textarea',
      section: 'Step 5: What Do You Want',
      placeholder: 'Be specific and vivid. What do you see, feel, experience?',
      required: true,
    },
    {
      id: 'health-goals',
      text: 'What do you want to achieve for your health and energy?',
      type: 'textarea',
      section: 'Step 5: What Do You Want',
      placeholder: 'Physical health, mental health, energy levels...',
    },
    {
      id: 'relationship-goals',
      text: 'What do you want for your relationships?',
      type: 'textarea',
      section: 'Step 5: What Do You Want',
      placeholder: 'Family, friends, romantic, professional relationships...',
    },
    {
      id: 'career-goals',
      text: 'What do you want to achieve professionally?',
      type: 'textarea',
      section: 'Step 5: What Do You Want',
      placeholder: 'Career, business, skills, impact...',
    },
    {
      id: 'financial-goals',
      text: 'What are your financial goals?',
      type: 'textarea',
      section: 'Step 5: What Do You Want',
      placeholder: 'Income, savings, investments, freedom...',
    },
    {
      id: 'personal-growth-goals',
      text: 'How do you want to grow as a person?',
      type: 'textarea',
      section: 'Step 5: What Do You Want',
      placeholder: 'Learning, mindset, habits, character...',
    },
    {
      id: 'experiences-wanted',
      text: 'What experiences do you want to have next year?',
      type: 'textarea',
      section: 'Step 5: What Do You Want',
      placeholder: 'Travel, adventures, milestones, bucket list items...',
    },
    {
      id: 'contribution-goals',
      text: 'How do you want to contribute to others?',
      type: 'textarea',
      section: 'Step 5: What Do You Want',
      placeholder: 'Impact, service, giving, community...',
    },

    // STEP 6: ACTION & PLAN
    {
      id: 'top-three-goals',
      text: 'What are your top 3 goals for next year?',
      type: 'textarea',
      section: 'Step 6: Action & Plan',
      placeholder: '1.\n2.\n3.',
      helpText: 'Be specific and measurable. These should be your non-negotiables.',
      required: true,
    },
    {
      id: 'first-steps',
      text: 'What are the first steps for each goal?',
      type: 'textarea',
      section: 'Step 6: Action & Plan',
      placeholder: 'Goal 1 first step:\nGoal 2 first step:\nGoal 3 first step:',
    },
    {
      id: 'habits-to-build',
      text: 'What new habits do you want to build?',
      type: 'textarea',
      section: 'Step 6: Action & Plan',
      placeholder: 'Daily or weekly habits that support your goals...',
    },
    {
      id: 'habits-to-break',
      text: 'What habits do you want to stop or change?',
      type: 'textarea',
      section: 'Step 6: Action & Plan',
      placeholder: 'Behaviors that no longer serve you...',
    },
    {
      id: 'accountability',
      text: 'How will you hold yourself accountable?',
      type: 'textarea',
      section: 'Step 6: Action & Plan',
      placeholder: 'Systems, people, check-ins...',
    },
    {
      id: 'potential-obstacles',
      text: 'What obstacles might you face, and how will you handle them?',
      type: 'textarea',
      section: 'Step 6: Action & Plan',
      placeholder: 'Anticipate challenges and plan responses...',
    },
    {
      id: 'support-needed',
      text: 'What support do you need, and from whom?',
      type: 'textarea',
      section: 'Step 6: Action & Plan',
      placeholder: 'People, resources, communities...',
    },
    {
      id: 'commitment-statement',
      text: 'Write a commitment statement to yourself for the coming year.',
      type: 'textarea',
      section: 'Step 6: Action & Plan',
      placeholder: 'I commit to...',
      required: true,
    },
    {
      id: 'closing-reflection',
      text: 'Any final thoughts or reflections as you close this review?',
      type: 'textarea',
      section: 'Step 6: Action & Plan',
      placeholder: 'Capture anything else on your mind...',
    },
  ],
}
