import { ReviewTemplate } from './types'

export const tiagoTemplate: ReviewTemplate = {
  slug: 'tiago-annual-review',
  name: "Tiago Forte's Annual Review",
  year: 2025,
  creator: {
    name: 'Tiago Forte',
    title: 'Author of Building a Second Brain',
    bio: 'A creative, memory-focused approach to annual reflection that emphasizes gratitude and connection.',
    websiteUrl: 'https://fortelabs.com',
  },
  intro: {
    headline: 'Remember. Connect. Create.',
    description: 'This review guides you through a three-phase journey: preparing your mind, remembering what mattered, and connecting insights to create your future. Embrace the emotional journey.',
    estimatedMinutes: 60,
  },
  questions: [
    // PHASE 1: PREPARATION
    {
      id: 'calendar-review',
      text: 'Open your calendar and scroll through the year. What events, meetings, or trips stand out to you?',
      type: 'textarea',
      section: 'Phase 1: Preparation',
      placeholder: 'List significant events from your calendar...',
      helpText: 'Let your calendar jog your memory before diving deeper.',
    },
    {
      id: 'photo-review',
      text: 'Scroll through your photos from this year. Which images bring up strong emotions or memories?',
      type: 'textarea',
      section: 'Phase 1: Preparation',
      placeholder: 'Describe the photos and memories they evoke...',
    },
    {
      id: 'notes-review',
      text: 'Browse your notes, journals, or second brain. What themes or ideas kept appearing?',
      type: 'textarea',
      section: 'Phase 1: Preparation',
      placeholder: 'Recurring themes, ideas, or questions...',
    },

    // PHASE 2: REMEMBER
    {
      id: 'peak-experiences',
      text: 'What were your peak experiences this year - moments of joy, awe, or deep satisfaction?',
      type: 'textarea',
      section: 'Phase 2: Remember',
      placeholder: 'Describe moments when you felt most alive...',
      required: true,
    },
    {
      id: 'meaningful-conversations',
      text: 'What were the most meaningful conversations you had this year?',
      type: 'textarea',
      section: 'Phase 2: Remember',
      placeholder: 'Who did you talk with? What did you discuss?',
    },
    {
      id: 'books-media',
      text: 'What books, podcasts, movies, or articles impacted you most?',
      type: 'textarea',
      section: 'Phase 2: Remember',
      placeholder: 'List the media that shaped your thinking...',
    },
    {
      id: 'new-people',
      text: 'Who are the new people you met this year that made an impression?',
      type: 'textarea',
      section: 'Phase 2: Remember',
      placeholder: 'New friends, colleagues, mentors, connections...',
    },
    {
      id: 'risks-taken',
      text: 'What risks did you take this year?',
      type: 'textarea',
      section: 'Phase 2: Remember',
      placeholder: 'Big or small - any time you stepped outside your comfort zone...',
    },
    {
      id: 'surprises',
      text: 'What surprised you this year?',
      type: 'textarea',
      section: 'Phase 2: Remember',
      placeholder: 'Unexpected events, realizations, or outcomes...',
    },
    {
      id: 'tough-moments',
      text: 'What were your toughest moments, and how did you get through them?',
      type: 'textarea',
      section: 'Phase 2: Remember',
      placeholder: 'Challenges, setbacks, difficult times...',
      required: true,
    },
    {
      id: 'proud-of',
      text: 'What are you most proud of from this year?',
      type: 'textarea',
      section: 'Phase 2: Remember',
      placeholder: 'Achievements, growth, things you did...',
      required: true,
    },
    {
      id: 'grateful-people',
      text: 'Who are you most grateful for this year?',
      type: 'textarea',
      section: 'Phase 2: Remember',
      placeholder: 'People who supported, inspired, or loved you...',
      required: true,
    },
    {
      id: 'favorite-places',
      text: 'What were your favorite places you visited or spent time in?',
      type: 'textarea',
      section: 'Phase 2: Remember',
      placeholder: 'Cities, homes, nature spots, workspaces...',
    },
    {
      id: 'new-skills',
      text: 'What new skills or abilities did you develop?',
      type: 'textarea',
      section: 'Phase 2: Remember',
      placeholder: 'Things you learned to do better...',
    },
    {
      id: 'creative-work',
      text: 'What creative work did you produce this year?',
      type: 'textarea',
      section: 'Phase 2: Remember',
      placeholder: 'Writing, art, projects, designs, code, music...',
    },
    {
      id: 'favorite-memories',
      text: 'If you could relive any moments from this year, which would they be?',
      type: 'textarea',
      section: 'Phase 2: Remember',
      placeholder: 'Your most treasured memories...',
    },

    // PHASE 3: CONNECT & CREATE
    {
      id: 'year-story',
      text: 'If this year were a chapter in your life story, what would you title it?',
      type: 'text',
      section: 'Phase 3: Connect & Create',
      placeholder: 'A title that captures the essence...',
      required: true,
    },
    {
      id: 'year-story-summary',
      text: 'Write a brief summary of this chapter - what was the narrative arc?',
      type: 'textarea',
      section: 'Phase 3: Connect & Create',
      placeholder: 'Beginning, middle, end - what\'s the story?',
    },
    {
      id: 'lessons-forward',
      text: 'What lessons from this year do you want to carry forward?',
      type: 'textarea',
      section: 'Phase 3: Connect & Create',
      placeholder: 'Wisdom you\'ve gained...',
      required: true,
    },
    {
      id: 'let-go',
      text: 'What do you want to let go of as you enter the new year?',
      type: 'textarea',
      section: 'Phase 3: Connect & Create',
      placeholder: 'Beliefs, habits, relationships, expectations...',
    },
    {
      id: 'next-year-feeling',
      text: 'How do you want to FEEL next year?',
      type: 'textarea',
      section: 'Phase 3: Connect & Create',
      placeholder: 'Emotions and states you want to cultivate...',
      helpText: 'Focus on feelings, not achievements.',
    },
    {
      id: 'next-year-identity',
      text: 'Who do you want to BECOME next year?',
      type: 'textarea',
      section: 'Phase 3: Connect & Create',
      placeholder: 'The person you\'re growing into...',
    },
    {
      id: 'next-year-create',
      text: 'What do you want to CREATE next year?',
      type: 'textarea',
      section: 'Phase 3: Connect & Create',
      placeholder: 'Projects, work, art, experiences...',
    },
    {
      id: 'next-year-experience',
      text: 'What do you want to EXPERIENCE next year?',
      type: 'textarea',
      section: 'Phase 3: Connect & Create',
      placeholder: 'Adventures, milestones, moments...',
    },
    {
      id: 'next-year-learn',
      text: 'What do you want to LEARN next year?',
      type: 'textarea',
      section: 'Phase 3: Connect & Create',
      placeholder: 'Skills, knowledge, wisdom...',
    },
    {
      id: 'word-for-next-year',
      text: 'Choose one word to guide your next year.',
      type: 'text',
      section: 'Phase 3: Connect & Create',
      placeholder: 'Your guiding word...',
      required: true,
    },
    {
      id: 'word-meaning',
      text: 'What does this word mean to you? How will you embody it?',
      type: 'textarea',
      section: 'Phase 3: Connect & Create',
      placeholder: 'Explain your word choice...',
    },
    {
      id: 'letter-to-future',
      text: 'Write a brief letter to yourself one year from now.',
      type: 'textarea',
      section: 'Phase 3: Connect & Create',
      placeholder: 'Dear Future Me...',
      helpText: 'What do you hope they\'ll be able to say when they read this?',
      required: true,
    },
    {
      id: 'three-priorities',
      text: 'What are your three biggest priorities for next year?',
      type: 'textarea',
      section: 'Phase 3: Connect & Create',
      placeholder: '1.\n2.\n3.',
      required: true,
    },
    {
      id: 'first-action',
      text: 'What is ONE action you can take in the first week of the new year toward your priorities?',
      type: 'textarea',
      section: 'Phase 3: Connect & Create',
      placeholder: 'Start small, start now...',
    },
    {
      id: 'gratitude-close',
      text: 'Close with gratitude: What are you thankful for as you end this review?',
      type: 'textarea',
      section: 'Phase 3: Connect & Create',
      placeholder: 'Express your gratitude...',
    },
  ],
}
